export const words = {
    easy: [
      { word: 'cat', hint: 'A common pet' },
      { word: 'sun', hint: 'It shines during the day' },
      { word: 'house', hint: 'Where people live' },
      { word: 'car', hint: 'Used for transportation' },
      { word: 'book', hint: 'Contains stories or information' },
      { word: 'apple', hint: 'A fruit that is red or green' },
      { word: 'water', hint: 'Essential for life' },
      { word: 'bird', hint: 'Has feathers and flies' },
      { word: 'ball', hint: 'Used in many sports' },
      { word: 'dog', hint: 'A loyal companion' },
      { word: 'moon', hint: 'Earth\'s natural satellite' },
      { word: 'flower', hint: 'Blooms in gardens' },
      { word: 'music', hint: 'Art form with sound' },
      { word: 'computer', hint: 'Used for processing information' },
    ],
    medium: [
      { word: 'python', hint: 'A programming language and a snake' },
      { word: 'planet', hint: 'Earth is one' },
      { word: 'galaxy', hint: 'Contains billions of stars' },
      { word: 'robot', hint: 'A machine that can perform tasks' },
      { word: 'ocean', hint: 'Covers most of the Earth\'s surface' },
      { word: 'mountain', hint: 'A tall natural elevation' },
      { word: 'forest', hint: 'A large area covered chiefly with trees' },
      { word: 'computer', hint: 'An electronic device for processing data' },
      { word: 'camera', hint: 'Used to capture photographs' },
      { word: 'guitar', hint: 'Musical instrument with strings' },
      { word: 'universe', hint: 'All of space and everything in it' },
      { word: 'dinosaur', hint: 'Extinct reptiles from prehistoric times' },
      { word: 'telescope', hint: 'Instrument for viewing distant objects' },
      { word: 'satellite', hint: 'Artificial object orbiting Earth' },
      { word: 'chemistry', hint: 'Study of matter and its changes' },
      { word: 'architecture', hint: 'Design and construction of buildings' },
    ],
    hard: [
      { word: 'astronomy', hint: 'The study of celestial objects' },
      { word: 'constellation', hint: 'A group of stars' },
      { word: 'nebula', hint: 'A cloud in space' },
      { word: 'quasar', hint: 'A very energetic and distant object' },
      { word: 'supernova', hint: 'An exploding star' },
      { word: 'blackhole', hint: 'A region of spacetime where gravity is extremely strong' },
      { word: 'cosmology', hint: 'The study of the universe as a whole' },
      { word: 'telescope', hint: 'Instrument for viewing distant objects' },
      { word: 'particle', hint: 'A tiny piece of matter' },
      { word: 'dimension', hint: 'A measure of space' },
      { word: 'biochemistry', hint: 'Chemistry of living organisms' },
      { word: 'meteorite', hint: 'Piece of rock from space that lands on Earth' },
      { word: 'molecule', hint: 'A group of atoms bonded together' },
      { word: 'algorithm', hint: 'A set of instructions for solving a problem' },
      { word: 'electromagnetism', hint: 'Interaction of electric and magnetic fields' }
    ],
  };
